ALTER TABLE vaults
    ADD COLUMN IF NOT EXISTS liquid_usdc DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS wsol_exposure_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reserve_status TEXT NOT NULL DEFAULT 'ok',
    ADD COLUMN IF NOT EXISTS execution_env TEXT,
    ADD COLUMN IF NOT EXISTS last_market_update BIGINT NOT NULL DEFAULT 0;
