[package]
name    = "arcadia-workers"
edition.workspace = true
version.workspace = true

[dependencies]
arcadia-core    = { workspace = true }
arcadia-db      = { workspace = true }
arcadia-decode  = { workspace = true }
arcadia-scoring = { workspace = true }
arcadia-chain   = { workspace = true }
arcadia-executor = { workspace = true }
arcadia-prices  = { workspace = true }

tokio        = { workspace = true }
sqlx         = { workspace = true }
redis        = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
chrono       = { workspace = true }
tracing      = { workspace = true }
anyhow       = { workspace = true }
rust_decimal = { workspace = true }
borsh        = { workspace = true }
base64       = { workspace = true }
bs58         = { workspace = true }
reqwest      = { workspace = true }

ed25519-dalek = { workspace = true }
curve25519-dalek = "4"
sha2          = { workspace = true }
